export const SCOUT_SETS = ['1º SET', '2º SET', 'GOLDEN GOL', 'SHOOT OUT'] as const

export const SCOUT_CONTROLE_JOGO = [
  'BOLA AO ALTO - INÍCIO',
  'PEDIDO DE TEMPO TÉCNICO',
  'RETORNO DO TEMPO TÉCNICO',
  'GOLDEN GOL',
  'FIM DO SET',
  'FIM DO JOGO',
  'SHOOT OUT',
] as const

export const SCOUT_EQUIPES = [
  'CEPRAEA',
  'ADM Maricá',
  'Campinas 360',
  'Niterói Rugby',
  'NR Beach',
  'Rio Handbeach',
  'IDEC',
  'América FC/ADHFT',
  'MHB — Milka Handbeach',
  'Buds Handbeach',
  'APCEF',
] as const

export const SCOUT_POSSE = ['CEPRAEA', 'Adversário'] as const

export const SCOUT_FASE_JOGO = [
  'Ataque posicionado',
  'Defesa posicionada',
  'Transição ofensiva direta',
  'Transição ofensiva indireta',
  'Transição defensiva direta',
  'Transição defensiva indireta',
  'Shoot-out',
  'Controle de jogo',
] as const

export const SCOUT_SISTEMAS = [
  'Ataque 3:1 ESP central + pivô destra',
  'Ataque 3:1 ESP central + pivô canhota',
  'Ataque 3:1 ESP lat direita canhota',
  'Ataque 3:1 ESP lat direita destra',
  'Ataque 4:0 ESP lat esquerda',
  'Ataque 4:0 ESP lat direita destra',
  'Ataque 4:0 ESP lat direita canhota',
  'Ataque 4:0 ESP central esquerda',
  'Ataque 4:0 ESP central direita canhota',
  'Ataque 4:0 ESP central direita destra',
  'Defesa 3x0',
  'Defesa 2x1',
  'Defesa 0x3',
  'Defesa 1x2',
  'Defesa individual',
  'Defesa mista',
  'Defesa API / Base / Solta',
  'Transição ofensiva direta 1x0 lat esquerda',
  'Transição ofensiva direta 1x0 lat esquerda + central',
  'Transição ofensiva direta 1x0 lat esquerda + central + pivô + lat direita',
  'Transição ofensiva direta 2x1 lat direita',
  'Transição ofensiva direta 2x1 lat direita + central',
  'Transição ofensiva direta 2x1 lat esquerda',
  'Transição ofensiva indireta 3:1 ESP central',
  'Transição ofensiva indireta 3:1 ESP lat esquerda',
  'Transição ofensiva indireta 3:1 ESP lat direita',
  'Transição ofensiva indireta 4:0 ESP lat esquerda',
  'Transição ofensiva indireta 4:0 ESP lat direita',
  'Transição ofensiva indireta 4:0 ESP central esquerda',
  'Transição ofensiva indireta 4:0 ESP central direita',
  'Transição defensiva direta 2x1',
  'Transição defensiva direta 3x0 - 1ª Base',
  'Transição defensiva direta 3x0 - 1ª Solta',
  'Transição defensiva direta 3x0 - 1ª API',
  'Transição defensiva direta 3x0',
  'Transição defensiva direta 0x3',
  'Transição defensiva direta individual alta',
  'Transição defensiva indireta 2x1',
  'Transição defensiva indireta 3x0',
  'Shoot-out ofensivo',
  'Shoot-out defensivo',
] as const

export const SCOUT_LADO_ACAO = [
  'Esquerda',
  'Centro',
  'Direita',
  'Área',
  'Lado da troca',
  'Lado oposto da troca',
  'Transição',
  'Shoot-out',
  'Não se aplica',
] as const

export const SCOUT_ATLETAS = [
  'Aline Mello',
  'Roberta Hernandez',
  'Carolina Peixinho',
  'Gabriela Peixinho',
  'Aline Kécia',
  'Bruna Xavier',
  'Beatriz Correia',
  'Fernanda Campbell',
  'Marleide Nunes',
  'Rafaela Dillmann',
  'Taís Almeida',
  'Carolina Bezerra',
  'Paola Wolff',
] as const

export const SCOUT_GOLEIRAS = ['Carolina Bezerra', 'Paola Wolff'] as const

export const SCOUT_FUNCOES_ATAQUE = [
  'Central',
  'Central Especialista',
  'Central Playmaker Esq',
  'Central Playmaker Dir',
  'Lateral esquerda',
  'Lateral direita',
  'Lateral Esquerda Especialista',
  'Lateral Direita Especialista',
  'Pivô',
  'Especialista',
  'Coringa',
  'Goleira passadora',
  'Shoot-out - Passadora',
  'Shoot-out - Cobradora',
] as const

export const SCOUT_FUNCOES_DEFESA = [
  'Base',
  'Solta',
  'API / Atrás da Pivô',
  'Avançada',
  'Goleira',
] as const

export const SCOUT_CATEGORIAS = [
  '1 - Ação técnica assertiva',
  '2 - Erro técnico',
  '3 - Assistência / ação que gera finalização',
  '4 - Erro de decisão',
  '5 - Recuperação / ação defensiva positiva',
  '6 - Falta / infração / ação irregular',
  '7 - Boa tomada de decisão',
  '8 - Passe de apoio',
  '9 - Desmarque',
] as const

export const SCOUT_ACOES_ATAQUE = [
  'Recepção segura na lateral esquerda',
  'Finalização de 1 ponto convertida',
  'Finalização de 2 pontos convertida',
  'Arremesso em giro convertido',
  'Arremesso em aérea convertido',
  'Infiltração pelo lado esquerdo com vantagem',
  'Ataque ao espaço vazio da defesa',
  'Finta curta para ganhar ângulo',
  'Passe rápido para continuidade do ataque',
  'Passe longo correto para lado oposto',
  'Passe para pivô em condição de finalização',
  'Passe para especialista em condição de finalização',
  'Troca de posição correta com a central',
  'Troca de posição correta com a pivô',
  'Fixação da defensora antes do passe',
  'Leitura correta do bloqueio defensivo',
  'Finalização com bom ângulo',
  'Ataque em superioridade bem executado',
  'Continuidade após pressão defensiva',
  'Tomada de decisão rápida na transição',
  'Recepção segura na lateral direita',
  'Ataque ao espaço entre base e API',
  'Ataque ao espaço entre base e solta',
  'Passe correto para pivô',
  'Passe correto para especialista',
  'Passe correto para central',
  'Posicionamento correto entre defensoras',
  'Recepção segura próxima à área',
  'Recepção aérea correta',
  'Giro convertido',
  'Aérea convertida',
  'Proteção da bola sem falta',
  'Bloqueio ofensivo legal',
  'Desmarque curto para receber',
  'Organização correta do ataque',
  'Passe inicial seguro',
  'Passe para lateral em vantagem',
  'Passe para pivô em vantagem',
  'Passe para especialista em vantagem',
  'Passe longo correto',
  'Passe aéreo correto',
  'Controle de ritmo do ataque',
  'Chamada correta do sistema',
  'Erro de recepção',
  'Passe errado',
  'Passe interceptado',
  'Arremesso para fora',
  'Arremesso bloqueado',
  'Arremesso sem ângulo',
  'Erro de tempo na aérea',
  'Erro de tempo no giro',
  'Pisou na área',
  'Perdeu a bola sob pressão',
  'Erro de substituição',
  'Arremesso precipitado',
  'Perda de bola por demora na decisão',
  'Assistência para pivô',
  'Assistência para especialista',
  'Assistência para central',
  'Assistência em aérea',
  'Passe que gera gol de 2 pontos',
  'Passe que gera tiro de 6m',
  'Assistência para lateral esquerda',
  'Assistência para lateral direita',
  'Forçou finalização marcada',
  'Forçou passe para pivô sem linha',
  'Não viu atleta livre',
  'Prendeu a bola e atrasou o ataque',
  'Não acelerou em vantagem numérica',
  'Não identificou pivô livre',
  'Não identificou especialista livre',
  'Falta de ataque',
  'Contato ofensivo ilegal',
  'Invasão da área',
  'Substituição irregular',
] as const

export const SCOUT_ACOES_DEFESA = [
  'Posicionamento central correto',
  'Comunicação defensiva efetiva',
  'Leitura correta da especialista central',
  'Leitura correta da pivô',
  'Fechamento do centro',
  'Fechamento da linha da área',
  'Cobertura da API',
  'Cobertura da solta',
  'Troca de marcação correta',
  'Flutuação entre pivô e especialista',
  'Indução do ataque para lateral',
  'Temporização da atacante com bola',
  'Bloqueio de arremesso',
  'Bloqueio após giro',
  'Bloqueio duplo correto',
  'Antecipação de passe central',
  'Pressão controlada sem abrir o centro',
  'Recuperação defensiva após perda',
  'Pressão correta na primeira linha',
  'Entrada correta na linha de passe',
  'Antecipação de passe',
  'Interceptação de passe',
  'Dissuasão na lateral',
  'Dissuasão na central',
  'Pressão na playmaker',
  'Recuo no tempo correto',
  'Subida no tempo correto',
  'Leitura correta do lado da troca',
  'Indução ao passe longo',
  'Indução ao erro técnico',
  'Fechamento da linha de passe para especialista',
  'Marcação indireta da especialista',
  'Posicionamento correto atrás da pivô',
  'Controle da pivô sem contato ilegal',
  'Fechamento da linha de passe para pivô',
  'Defesa do passe aéreo para pivô',
  'Antecipação do passe para pivô',
  'Falsa liberdade bem executada',
  'Acompanhamento da pivô',
  'Bloqueio do giro da pivô',
  'Proteção contra aérea',
  'Erro de posicionamento central',
  'Saiu do centro sem cobertura',
  'Perdeu a especialista',
  'Perdeu a pivô',
  'Chegou atrasada no bloqueio',
  'Falhou na comunicação',
  'Subiu fora do tempo',
  'Recuou tarde',
  'Abriu passe longo fácil',
  'Foi batida na primeira pressão',
  'Não retornou após pressão',
  'Deu liberdade real para finalização',
  'Errou o tempo da falsa liberdade',
  'Deixou aérea entrar',
  'Não fechou a linha da área',
  'Escolheu pressionar quando deveria proteger o centro',
  'Pressionou sem cobertura',
  'Tentou roubar bola sem leitura',
  'Marcou a bola e esqueceu a pivô',
  'Interceptação de passe',
  'Recuperação de bola',
  'Indução de erro ofensivo',
  'Forçou passe longo',
  'Forçou arremesso ruim',
  'Gerou falta de ataque',
  'Bloqueio que impediu gol',
  'Roubo de bola',
  'Passe recuperado',
  'Gerou contra-ataque',
  'Bloqueio de giro',
  'Bloqueio duplo efetivo',
  'Contato ilegal',
  'Contato no ar',
  'Tiro de 6m cometido',
  'Invasão da área',
  'Falta defensiva desnecessária',
  'Contato ilegal na pivô',
] as const

export const SCOUT_ACOES_GOLEIRA = [
  'Defesa de arremesso de 1 ponto',
  'Defesa de arremesso de 2 pontos',
  'Passe de saída correto',
  'Passe longo para transição',
  'Passe errado na saída',
  'Defesa no shoot-out',
  'Gol de goleira',
  'Erro de posicionamento',
  'Reposição rápida',
  'Reposição lenta',
] as const

export const SCOUT_REPOSICAO = [
  'Troca lado direito',
  'Troca lado esquerdo',
  'Entrada da especialista',
  'Saída da goleira',
  'Entrada defensiva',
  'Saída defensiva',
  'Reposição rápida',
  'Reposição lenta',
  'Reposição direta',
  'Reposição indireta',
  'Erro de substituição',
  'Atraso na troca',
  'Entrada correta da especialista',
] as const

export const SCOUT_RESULTADO_COLETIVO = [
  'Gol 1 ponto',
  'Gol 2 pontos',
  'Gol de giro 2 pontos',
  'Gol de aérea 2 pontos',
  'Gol de giro 1 ponto — erro técnico',
  'Gol de aérea 1 ponto — erro técnico',
  'Giro sem validade de 2 pontos',
  'Aérea sem validade de 2 pontos',
  'Giro bloqueado',
  'Aérea bloqueada',
  'Giro para fora',
  'Aérea para fora',
  'Gol sofrido 1 ponto',
  'Gol sofrido 2 pontos',
  'Defesa da goleira',
  'Finalização para fora',
  'Finalização bloqueada',
  'Perda de bola',
  'Recuperação de bola',
  'Falta de ataque',
  'Falta defensiva',
  'Tiro de 6m a favor',
  'Tiro de 6m contra',
  'Exclusão a favor',
  'Exclusão contra',
  'Shoot-out convertido',
  'Shoot-out perdido',
  'Erro de substituição',
  'Sem finalização',
  'Revisar',
] as const

export const SCOUT_RESULTADO_INDIVIDUAL = [
  'Acerto',
  'Erro técnico',
  'Assistência',
  'Erro de decisão',
  'Recuperação defensiva',
  'Infração',
  'Neutro',
  'Revisar',
] as const

export const SCOUT_ANALISE = ['Positiva', 'Neutra', 'Negativa', 'Revisar'] as const

export const SCOUT_ACOES_ESPECIALISTA_CENTRAL = [
  'Passe de central do chão para giro da lateral esquerda',
  'Passe de central saltando para giro da lateral esquerda',
  'Passe de central do chão após finta de passe para giro da lateral esquerda',
  'Passe de central saltando para aérea da lateral esquerda',
  'Passe de central do chão para giro da lateral direita',
  'Passe de central saltando para giro da lateral direita',
  'Passe de central do chão após finta de passe para giro da lateral direita',
  'Passe de central saltando para aérea da lateral direita',
  'Passe de central sem olhar para lateral esquerda',
  'Passe de central sem olhar para lateral direita',
  'Passe de central sem olhar para pivô',
  'Passe de central para aérea da pivô',
  'Passe de central para giro da pivô',
  'Passe de central após fixar a Base',
  'Passe de central após atrair a Solta',
  'Passe de central após deslocar a API',
  'Finta de passe e passe para aérea',
  'Finta de passe e passe para giro',
  'Finta de arremesso e passe para pivô',
  'Finta de arremesso e passe para lateral',
  'Passe que quebra a defesa 3x0',
  'Passe que quebra a defesa 2x1',
  'Erro de tempo no passe para giro',
  'Erro de tempo no passe para aérea',
  'Erro de leitura da defesa',
  'Erro de decisão após finta',
] as const

export const SCOUT_ORIGEM_BOLA_ESPECIALISTA = [
  'Bola vindo da lateral esquerda',
  'Bola vindo da lateral direita',
  'Bola vindo da pivô',
  'Bola vindo da goleira',
  'Bola vindo da central',
  'Bola vindo de recuperação',
  'Bola vindo de reposição',
  'Bola sem mexida prévia',
  'Bola após circulação completa',
  'Bola após circulação parcial',
] as const

export const SCOUT_MEXIDA_INICIAL = [
  'Sem mexida',
  'Mexida rápida',
  'Mexida lenta',
  'Mexida alternada',
  'Mexida de mão em mão',
  'Circulação completa',
  'Circulação parcial',
] as const

export const SCOUT_COMPORTAMENTO_DEFESA = [
  'Solta não foi fixada',
  'Solta foi fixada pela lateral direita',
  'Solta foi fixada pela lateral esquerda',
  'Solta subiu na central',
  'Solta fechou linha de passe',
  'Base permaneceu no centro',
  'Base saiu para pivô',
  'Base saiu para especialista',
  'API permaneceu na pivô',
  'API dividiu pivô e lateral',
  'API saiu para lateral',
  'Defesa deslocou para direita',
  'Defesa deslocou para esquerda',
  'Defesa não deslocou',
  'Defesa induziu sobra na lateral direita',
  'Defesa induziu sobra na lateral esquerda',
] as const

export const SCOUT_BOOLEANO_TATICO = ['Sim', 'Não', 'Parcial'] as const

export const SCOUT_MOMENTO_ATAQUE_ESPECIALISTA = [
  'Atacou cedo demais',
  'Atacou no tempo correto',
  'Atacou tarde demais',
  'Atacou sem fixar a Solta',
  'Atacou após fixar a Solta',
  'Atacou sem deslocar Base',
  'Atacou após deslocar Base',
  'Atacou sem deslocar API',
  'Atacou após deslocar API',
  'Atacou com defesa organizada',
  'Atacou com defesa em deslocamento',
  'Atacou com defesa desequilibrada',
] as const

export const SCOUT_RITMO_ESPECIALISTA = [
  'Ritmo constante',
  'Acelerou',
  'Desacelerou',
  'Quebra de ritmo',
  'Atacou após pausa',
  'Aproximação lenta e aceleração',
  'Postura pouco ofensiva e ataque rápido',
  'Postura agressiva e passe',
  'Simulou ataque e passou',
  'Chamou atenção e distribuiu',
] as const

export const SCOUT_PREVISIBILIDADE_ESPECIALISTA = [
  'Previsível',
  'Parcialmente previsível',
  'Imprevisível',
  'Defesa antecipou a ação',
  'Defesa não antecipou',
  'Defesa mordeu a finta',
  'Defesa esperou e controlou',
  'Especialista repetiu padrão anterior',
  'Especialista quebrou padrão anterior',
  'Especialista variou tempo de ataque',
] as const

export const SCOUT_DECISAO_FINAL_ESPECIALISTA = [
  'Finalizou em giro',
  'Finalizou em aérea',
  'Finalizou simples',
  'Passou para lateral esquerda',
  'Passou para lateral direita',
  'Passou para pivô',
  'Deu assistência para gol de 2 pontos',
  'Gerou tiro de 6m',
  'Fixou a Solta e passou',
  'Fixou a Base e passou',
  'Fixou a API e passou',
  'Forçou finalização marcada',
  'Forçou passe sem linha',
  'Perdeu bola',
  'Errou tempo de passe',
  'Errou leitura da defesa',
] as const

export const SCOUT_TIPO_FINALIZACAO = [
  'Arremesso simples',
  'Giro',
  'Aérea',
  'Ponte aérea',
  '360',
  'Arremesso da especialista',
  'Arremesso da goleira',
  'Shoot-out',
  'Tiro de 6m',
  'Não se aplica',
] as const

export const SCOUT_PONTUACAO = ['0 ponto', '1 ponto', '2 pontos'] as const
export const SCOUT_VALIDADE_TECNICA = ['Válida', 'Erro técnico', 'Revisar'] as const

export const SCOUT_SHOOTOUT_OFENSIVO = [
  'Lançamento direto da goleira para cobradora',
  'Lançamento curto da goleira para cobradora',
  'Lançamento longo da goleira para cobradora',
  'Lançamento alto para recepção aérea',
  'Lançamento baixo para recepção em velocidade',
  'Passe da goleira no tempo correto',
  'Passe da goleira atrasado',
  'Passe da goleira adiantado',
  'Passe da goleira interceptado',
  'Recepção segura da cobradora',
  'Erro de recepção da cobradora',
  'Finta curta na goleira',
  'Finta longa na goleira',
  'Finta de corpo',
  'Finta de arremesso',
  'Giro no shoot-out',
  'Aérea no shoot-out',
  'Finalização direta',
  'Finalização em giro',
  'Finalização em aérea',
  'Finalização por cobertura',
  'Shoot-out convertido',
  'Shoot-out perdido',
] as const

export const SCOUT_SHOOTOUT_DEFENSIVO = [
  'Goleira leu o lançamento',
  'Goleira saiu no tempo correto',
  'Goleira antecipou demais',
  'Goleira atrasou a saída',
  'Goleira fechou o ângulo',
  'Goleira abriu o ângulo',
  'Goleira induziu a finalização',
  'Goleira defendeu finalização direta',
  'Goleira defendeu giro',
  'Goleira defendeu aérea',
  'Goleira forçou finalização para fora',
  'Goleira tocou na bola',
  'Goleira cometeu tiro de 6m',
  'Goleira caiu antes da decisão',
  'Goleira esperou bem a cobradora',
  'Defesa venceu o shoot-out',
  'Defesa perdeu o shoot-out',
] as const
