export const SCOUT_SETS = ['1º SET', '2º SET', 'GOLDEN GOL', 'SHOOT OUT'] as const

export const SCOUT_CONTROLE_JOGO = [
  'BOLA AO ALTO - INÍCIO',
  'PEDIDO DE TEMPO TÉCNICO',
  'RETORNO DO TEMPO TÉCNICO',
  'GOLDEN GOL',
  'FIM DO SET',
  'FIM DO JOGO',
  'SHOOT OUT',
] as const

export const SCOUT_EQUIPES = [
  'CEPRAEA',
  'ADM Maricá',
  'Campinas 360',
  'Niterói Rugby',
  'NR Beach',
  'Rio Handbeach',
  'IDEC',
  'América FC/ADHFT',
  'MHB — Milka Handbeach',
  'Buds Handbeach',
  'APCEF',
] as const

export const SCOUT_POSSE = ['CEPRAEA', 'Adversário'] as const

export const SCOUT_FASE_JOGO = [
  'Ataque posicionado',
  'Defesa posicionada',
  'Transição ofensiva direta',
  'Transição ofensiva indireta',
  'Transição defensiva direta',
  'Transição defensiva indireta',
  'Shoot-out',
  'Controle de jogo',
] as const

export const SCOUT_SISTEMAS = [
  'Ataque 3:1 ESP central + pivô destra',
  'Ataque 3:1 ESP central + pivô canhota',
  'Ataque 3:1 ESP lat direita canhota',
  'Ataque 3:1 ESP lat direita destra',
  'Ataque 4:0 ESP lat esquerda',
  'Ataque 4:0 ESP lat direita destra',
  'Ataque 4:0 ESP lat direita canhota',
  'Ataque 4:0 ESP central esquerda',
  'Ataque 4:0 ESP central direita canhota',
  'Ataque 4:0 ESP central direita destra',
  'Defesa 3x0',
  'Defesa 2x1',
  'Defesa 0x3',
  'Defesa 1x2',
  'Defesa individual',
  'Defesa mista',
  'Defesa API / Base / Solta',
  'Transição ofensiva direta 1x0 lat esquerda',
  'Transição ofensiva direta 1x0 lat esquerda + central',
  'Transição ofensiva direta 1x0 lat esquerda + central + pivô + lat direita',
  'Transição ofensiva direta 2x1 lat direita',
  'Transição ofensiva direta 2x1 lat direita + central',
  'Transição ofensiva direta 2x1 lat esquerda',
  'Transição ofensiva indireta 3:1 ESP central',
  'Transição ofensiva indireta 3:1 ESP lat esquerda',
  'Transição ofensiva indireta 3:1 ESP lat direita',
  'Transição ofensiva indireta 4:0 ESP lat esquerda',
  'Transição ofensiva indireta 4:0 ESP lat direita',
  'Transição ofensiva indireta 4:0 ESP central esquerda',
  'Transição ofensiva indireta 4:0 ESP central direita',
  'Transição defensiva direta 2x1',
  'Transição defensiva direta 3x0 - 1ª Base',
  'Transição defensiva direta 3x0 - 1ª Solta',
  'Transição defensiva direta 3x0 - 1ª API',
  'Transição defensiva direta 3x0',
  'Transição defensiva direta 0x3',
  'Transição defensiva direta individual alta',
  'Transição defensiva indireta 2x1',
  'Transição defensiva indireta 3x0',
  'Shoot-out ofensivo',
  'Shoot-out defensivo',
] as const

export const SCOUT_LADO_ACAO = [
  'Esquerda',
  'Centro',
  'Direita',
  'Área',
  'Lado da troca',
  'Lado oposto da troca',
  'Transição',
  'Não se aplica',
] as const

export const SCOUT_ATLETAS = [
  'Aline Mello',
  'Roberta Hernandez',
  'Carolina Peixinho',
  'Gabriela Peixinho',
  'Aline Kécia',
  'Bruna Xavier',
  'Beatriz Correia',
  'Fernanda Campbell',
  'Marleide Nunes',
  'Rafaela Dillmann',
  'Taís Almeida',
  'Carolina Bezerra',
  'Paola Wolff',
] as const

export const SCOUT_GOLEIRAS = ['Carolina Bezerra', 'Paola Wolff'] as const

export const SCOUT_FUNCOES_ATAQUE = [
  'Central',
  'Lateral esquerda',
  'Lateral direita',
  'Pivô',
  'Especialista',
  'Coringa',
  'Goleira passadora',
] as const

export const SCOUT_FUNCOES_DEFESA = ['Base', 'Solta', 'API', 'Goleira'] as const

export const SCOUT_CATEGORIAS = [
  '1 - Ação técnica assertiva',
  '2 - Erro técnico',
  '3 - Assistência / ação que gera finalização',
  '4 - Erro de decisão',
  '5 - Recuperação / ação defensiva positiva',
  '6 - Falta / infração / ação irregular',
] as const

export const SCOUT_ACOES_ATAQUE = [
  'Recepção segura na lateral esquerda',
  'Finalização de 1 ponto convertida',
  'Finalização de 2 pontos convertida',
  'Arremesso em giro convertido',
  'Arremesso em aérea convertido',
  'Infiltração pelo lado esquerdo com vantagem',
  'Ataque ao espaço vazio da defesa',
  'Finta curta para ganhar ângulo',
  'Passe rápido para continuidade do ataque',
  'Passe longo correto para lado oposto',
  'Passe para pivô em condição de finalização',
  'Passe para especialista em condição de finalização',
  'Troca de posição correta com a central',
  'Troca de posição correta com a pivô',
  'Fixação da defensora antes do passe',
  'Leitura correta do bloqueio defensivo',
  'Finalização com bom ângulo',
  'Ataque em superioridade bem executado',
  'Continuidade após pressão defensiva',
  'Tomada de decisão rápida na transição',
  'Recepção segura na lateral direita',
  'Ataque ao espaço entre base e API',
  'Ataque ao espaço entre base e solta',
  'Passe correto para pivô',
  'Passe correto para especialista',
  'Passe correto para central',
  'Posicionamento correto entre defensoras',
  'Recepção segura próxima à área',
  'Recepção aérea correta',
  'Giro convertido',
  'Aérea convertida',
  'Proteção da bola sem falta',
  'Bloqueio ofensivo legal',
  'Desmarque curto para receber',
  'Organização correta do ataque',
  'Passe inicial seguro',
  'Passe para lateral em vantagem',
  'Passe para pivô em vantagem',
  'Passe para especialista em vantagem',
  'Passe longo correto',
  'Passe aéreo correto',
  'Controle de ritmo do ataque',
  'Chamada correta do sistema',
  'Erro de recepção',
  'Passe errado',
  'Passe interceptado',
  'Arremesso para fora',
  'Arremesso bloqueado',
  'Arremesso sem ângulo',
  'Erro de tempo na aérea',
  'Erro de tempo no giro',
  'Pisou na área',
  'Perdeu a bola sob pressão',
  'Erro de substituição',
  'Arremesso precipitado',
  'Perda de bola por demora na decisão',
  'Assistência para pivô',
  'Assistência para especialista',
  'Assistência para central',
  'Assistência em aérea',
  'Passe que gera gol de 2 pontos',
  'Passe que gera tiro de 6m',
  'Assistência para lateral esquerda',
  'Assistência para lateral direita',
  'Forçou finalização marcada',
  'Forçou passe para pivô sem linha',
  'Não viu atleta livre',
  'Prendeu a bola e atrasou o ataque',
  'Não acelerou em vantagem numérica',
  'Não identificou pivô livre',
  'Não identificou especialista livre',
  'Falta de ataque',
  'Contato ofensivo ilegal',
  'Invasão da área',
  'Substituição irregular',
] as const

export const SCOUT_ACOES_DEFESA = [
  'Posicionamento central correto',
  'Comunicação defensiva efetiva',
  'Leitura correta da especialista central',
  'Leitura correta da pivô',
  'Fechamento do centro',
  'Fechamento da linha da área',
  'Cobertura da API',
  'Cobertura da solta',
  'Troca de marcação correta',
  'Flutuação entre pivô e especialista',
  'Indução do ataque para lateral',
  'Temporização da atacante com bola',
  'Bloqueio de arremesso',
  'Bloqueio após giro',
  'Bloqueio duplo correto',
  'Antecipação de passe central',
  'Pressão controlada sem abrir o centro',
  'Recuperação defensiva após perda',
  'Pressão correta na primeira linha',
  'Entrada correta na linha de passe',
  'Antecipação de passe',
  'Interceptação de passe',
  'Dissuasão na lateral',
  'Dissuasão na central',
  'Pressão na playmaker',
  'Recuo no tempo correto',
  'Subida no tempo correto',
  'Leitura correta do lado da troca',
  'Indução ao passe longo',
  'Indução ao erro técnico',
  'Fechamento da linha de passe para especialista',
  'Marcação indireta da especialista',
  'Posicionamento correto atrás da pivô',
  'Controle da pivô sem contato ilegal',
  'Fechamento da linha de passe para pivô',
  'Defesa do passe aéreo para pivô',
  'Antecipação do passe para pivô',
  'Falsa liberdade bem executada',
  'Acompanhamento da pivô',
  'Bloqueio do giro da pivô',
  'Proteção contra aérea',
  'Erro de posicionamento central',
  'Saiu do centro sem cobertura',
  'Perdeu a especialista',
  'Perdeu a pivô',
  'Chegou atrasada no bloqueio',
  'Falhou na comunicação',
  'Subiu fora do tempo',
  'Recuou tarde',
  'Abriu passe longo fácil',
  'Foi batida na primeira pressão',
  'Não retornou após pressão',
  'Deu liberdade real para finalização',
  'Errou o tempo da falsa liberdade',
  'Deixou aérea entrar',
  'Não fechou a linha da área',
  'Escolheu pressionar quando deveria proteger o centro',
  'Pressionou sem cobertura',
  'Tentou roubar bola sem leitura',
  'Marcou a bola e esqueceu a pivô',
  'Interceptação de passe',
  'Recuperação de bola',
  'Indução de erro ofensivo',
  'Forçou passe longo',
  'Forçou arremesso ruim',
  'Gerou falta de ataque',
  'Bloqueio que impediu gol',
  'Roubo de bola',
  'Passe recuperado',
  'Gerou contra-ataque',
  'Bloqueio de giro',
  'Bloqueio duplo efetivo',
  'Contato ilegal',
  'Contato no ar',
  'Tiro de 6m cometido',
  'Invasão da área',
  'Falta defensiva desnecessária',
  'Contato ilegal na pivô',
] as const

export const SCOUT_ACOES_GOLEIRA = [
  'Defesa de arremesso de 1 ponto',
  'Defesa de arremesso de 2 pontos',
  'Passe de saída correto',
  'Passe longo para transição',
  'Passe errado na saída',
  'Defesa no shoot-out',
  'Gol de goleira',
  'Erro de posicionamento',
  'Reposição rápida',
  'Reposição lenta',
] as const

export const SCOUT_REPOSICAO = [
  'Troca lado direito',
  'Troca lado esquerdo',
  'Entrada da especialista',
  'Saída da goleira',
  'Entrada defensiva',
  'Saída defensiva',
  'Reposição rápida',
  'Reposição lenta',
  'Reposição direta',
  'Reposição indireta',
  'Erro de substituição',
  'Atraso na troca',
  'Entrada correta da especialista',
] as const

export const SCOUT_RESULTADO_COLETIVO = [
  'Gol 1 ponto',
  'Gol 2 pontos',
  'Gol sofrido 1 ponto',
  'Gol sofrido 2 pontos',
  'Defesa da goleira',
  'Finalização para fora',
  'Finalização bloqueada',
  'Perda de bola',
  'Recuperação de bola',
  'Falta de ataque',
  'Falta defensiva',
  'Tiro de 6m a favor',
  'Tiro de 6m contra',
  'Exclusão a favor',
  'Exclusão contra',
  'Shoot-out convertido',
  'Shoot-out perdido',
  'Erro de substituição',
  'Sem finalização',
  'Revisar',
] as const

export const SCOUT_RESULTADO_INDIVIDUAL = [
  'Acerto',
  'Erro técnico',
  'Assistência',
  'Erro de decisão',
  'Recuperação defensiva',
  'Infração',
  'Neutro',
  'Revisar',
] as const

export const SCOUT_ANALISE = ['Positiva', 'Neutra', 'Negativa', 'Revisar'] as const
